export const FETCH_COURSES = "FETCH_COURSES";

export const ADD_COURSE = "ADD_COURSE";
export const TOGGLE_DISPLAY_COURSE = "TOGGLE_DISPLAY_COURSE";
export const TOGGLE_CREATE_COURSE = "TOGGLE_CREATE_COURSE";
